### ISSUE TITLE
Incorrect comment generation

### ISSUE THREAD

**Issue by tritao** [mono/CppSharp#453]
C++ code:

```cpp
/// Hash set/map base class.
/** Note that to prevent extra memory use due to vtable pointer, %HashBase intentionally does not declare a virtual destructor
    and therefore %HashBase pointers should never be used.
  */
class URHO3D_API HashBase
```

Generated code:

```csharp
        /// <summary>
        /// <para>Hash set/map base class. Note that to prevent extra memory use
        /// due to vtable pointer, %HashBase intentionally does not declare a virtual
        /// destructor and therefore %HashBase pointers should never be used.</para>
        /// </summary>
        /// <remarks>
        /// <para>/// Hash set/map base class.
</para>
        /// <para>/** Note that to prevent extra memory use due to vtable pointer,
        /// %HashBase intentionally does not declare a virtual destructor
</para>
        /// <para>    and therefore %HashBase pointers should never be used.
        /// </para>
        /// <para>  */</para>
        /// </remarks>
        public unsafe partial class HashBase : IDisposable
```

**Comment by genuinelucifer** [comment]
I guess this one is solved because i used:
```C#
/// Hash set/map base class.
/** Note that to prevent extra memory use due to vtable pointer, %HashBase intentionally does not declare a virtual destructor
and therefore %HashBase pointers should never be used.
*/
class DLL_API HashBase {};
```
which generated:
```C#
    /// <summary>
    /// <para>Hash set/map base class. Note that to prevent extra memory use
    /// due to vtable pointer, %HashBase intentionally does not declare a virtual
    /// destructor and therefore %HashBase pointers should never be used.</para>
    /// </summary>
    /// <remarks>
    /// <para>/// Hash set/map base class.</para>
    /// <para></para>
    /// <para>/** Note that to prevent extra memory use due to vtable pointer,
    /// %HashBase intentionally does not declare a virtual destructor</para>
    /// <para></para>
    /// <para>and therefore %HashBase pointers should never be used.</para>
    /// <para></para>
    /// <para>*/</para>
    /// </remarks>
    public unsafe partial class HashBase : IDisposable
```

**Comment by tritao** [comment]
I'm still seeing problems related to this:

```
            /// <summary>
            ///
            /// <para>/////////////////////////////////////////////////////////////////////
            //////</para>
            /// </summary>
            /// <remarks>
            ///
            /// <para>/////////////////////////////////////////////////////////////////////
            /////////</para>
            /// </remarks>
            public unsafe partial class shared_memory_object : IDisposable
```

**Comment by ddobrev** [comment]
Fixed by 287ad23.

**Comment by tritao** [comment]
Still getting issues related to comment generation.

You can see them on the diffs here: https://github.com/tritao/LLDBSharp/commit/26436886f4a5f8d4423e4e07ab90fb2e12bead8c

**Comment by tritao** [comment]
```
Unhandled Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException () in /private/tmp/source-mono-mac-4.2.0-branch/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.1/external/referencesource/mscorlib/system/throwhelper.cs:line 56
   at System.Collections.Generic.List`1[T].get_Item (Int32 index) in <filename unknown>:line 0
   at CppSharp.Generators.CSharp.CSharpCommentPrinter.TrimSection (System.Collections.Generic.List`1 commentLines, Int32 start, Int32 end) in <filename unknown>:line 0
   at CppSharp.Generators.CSharp.CSharpCommentPrinter.CommentToString (CppSharp.AST.Comment comment, System.String commentPrefix) in <filename unknown>:line 0
   at CppSharp.Generators.CSharp.CSharpTextTemplate.GenerateComment (CppSharp.AST.RawComment comment) in <filename unknown>:line 0
   at CppSharp.Generators.CSharp.CSharpTextTemplate.GenerateDeclarationCommon (CppSharp.AST.Declaration decl) in <filename unknown>:line 0
   at CppSharp.Generators.CSharp.CSharpTextTemplate.GenerateMethod (CppSharp.AST.Method method, CppSharp.AST.Class class) in <filename
```

**Comment by realvictorprm** [comment]
We definitely need to fix this one

**Comment by ktopouzi** [comment]
For the comment that is generated [above](https://github.com/mono/CppSharp/issues/453#issuecomment-312709472), original found [here](https://github.com/glfw/glfw/blob/8e899ccc29cc082f8d373718f1881ef5b8863f84/include/GLFW/glfw3.h#L2289), i was able to fix the empty lines and some of the missing content such as:
* `@brief`
* `@note`
* `@reentrancy`
* `@since`

Clang seems to have a [bug](https://bugs.llvm.org/show_bug.cgi?id=33948) with VerbatimComments `@error`, `@ingroup`, `@ref` so i wasn't able to fix them. The `@sa` tag is fairly related with `@ref` and for that reason it is unsupported as well. Also i was able to fix the leftovers of the `@thread_safety` tag since its a custom one and there is no support for now.

**Comment by tritao** [comment]
Thanks for the improvements @ktopouzi.
