### ISSUE TITLE
Segmentation Fault While Compiling on Mac OS (Xcode 9)

### ISSUE THREAD

**Issue by KallynGowdyYetiCGI** [mono/CppSharp#954]
##### Brief Description

Compiling CppSharp on MacOS Sierra produces a `SIGSEGV`.

Using the steps listed in this document: [GettingStarted.md](https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md).
In particular, I'm running:

```
> cd build
> ./premake5-osx --file=scripts/LLVM.lua download_llvm
> ./premake5-osx gmake
> make -C gmake config=release_x64
```

It appears to download LLVM (`llvm-cad143-macosx-x64-Release.tar.xz`) and create the make files just fine, but actually building the project fails.

At first, I thought that the architectures were getting mixed up and I was somehow running a 32-bit version of LLVM or Clang but a 64-bit version of mono or vice-versa, but after looking at all of my versions and compiling with the suggested flags I don't think it is likely to be the issue.

If anyone has any ideas for what is going wrong, they would be appreciated.

**OS:** macOS Sierra (Version 10.12.6)
**Mono:**
```
Mono JIT compiler version 5.2.0.104 (2017-04/4a0006f Wed May 10 05:06:51 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen (concurrent by default)
```
**Clang:**
```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
**XCode:** Both XCode 9 Beta 5 (9M202q) and XCode 8.3.3 (8E3004b) installed
**GCC:** 
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
**Commit Hash:** [b965ac](https://github.com/mono/CppSharp/commit/b965aca3a2a694c5fd7d70bda79f29fffcccd04a)

##### Used headers

N/A

##### Used settings

Target: Clang

##### Stack trace or incompilable generated code

(I'll split it into parts to make it easier to understand)

#### Running `./premake5-osx gmake` (works fine):

```
Using debug LLVM build: /Users/kal/YetiCode/CppSharp/build/scripts/llvm-cad143-macosx-x64-Debug
Using release LLVM build: /Users/kal/YetiCode/CppSharp/build/scripts/llvm-cad143-macosx-x64-Release
Generating CppSharp build configuration file 'BuildConfig.cs'
Building configurations...
Running action 'gmake'...
Generated gmake/Makefile...
Generated gmake/projects/CppSharp.make...
Generated gmake/projects/CppSharp.AST.make...
Generated gmake/projects/CppSharp.CppParser.make...
Generated gmake/projects/Std-symbols.make...
Generated gmake/projects/CppSharp.Parser.CSharp.make...
Generated gmake/projects/CppSharp.Parser.Gen.make...
Generated gmake/projects/CppSharp.Parser.make...
Generated gmake/projects/CppSharp.CLI.make...
Generated gmake/projects/CppSharp.Generator.make...
Generated gmake/projects/CppSharp.Generator.Tests.make...
Generated gmake/projects/CppSharp.Runtime.make...
Generated gmake/projects/CLI.Gen.make...
Generated gmake/projects/CLI.Native.make...
Generated gmake/projects/Common.Gen.make...
Generated gmake/projects/Common.Native.make...
Generated gmake/projects/Common.CSharp.make...
Generated gmake/projects/Common.Tests.CSharp.make...
Generated gmake/projects/CSharp.Gen.make...
Generated gmake/projects/CSharp.Native.make...
Generated gmake/projects/CSharp.CSharp.make...
Generated gmake/projects/CSharp.Tests.CSharp.make...
Generated gmake/projects/Encodings.Gen.make...
Generated gmake/projects/Encodings.Native.make...
Generated gmake/projects/Encodings.CSharp.make...
Generated gmake/projects/Encodings.Tests.CSharp.make...
Generated gmake/projects/NamespacesBase.Native.make...
Generated gmake/projects/NamespacesBase.CSharp.make...
Generated gmake/projects/NamespacesDerived.Gen.make...
Generated gmake/projects/NamespacesDerived.Native.make...
Generated gmake/projects/NamespacesDerived.CSharp.make...
Generated gmake/projects/NamespacesDerived.Tests.CSharp.make...
Generated gmake/projects/StandardLib.Gen.make...
Generated gmake/projects/StandardLib.Native.make...
Generated gmake/projects/VTables.Gen.make...
Generated gmake/projects/VTables.Native.make...
Generated gmake/projects/VTables.CSharp.make...
Generated gmake/projects/VTables.Tests.CSharp.make...
Done (212ms).
```

####  Running `make -C gmake config=release_x64 verbose=true`:

- Other projects build fine:
```
==== Building CppSharp (release_x64) ====
Creating ../lib/Release_x64
mkdir -p ../lib/Release_x64
Creating ../obj/Release_x64/x64/Release/CppSharp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp/CppSharp.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.dll /unsafe /debug /noconfig /t:library   /r:System /r:System.Core /r:../../../deps/vs2017/Microsoft.VisualStudio.Setup.Configuration.Interop @../obj/Release_x64/x64/Release/CppSharp/CppSharp.rsp
==== Building CppSharp.AST (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.AST
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.AST
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.AST/CppSharp.AST.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.AST.dll /debug /noconfig /t:library   /r:System /r:System.Core @../obj/Release_x64/x64/Release/CppSharp.AST/CppSharp.AST.rsp
==== Building CppSharp.CppParser (release_x64) ====
AST.cpp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.CppParser
clang++   -MMD -MP -DNDEBUG -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../../scripts/llvm-cad143-macosx-x64-Release/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/lib -I../../scripts/llvm-cad143-macosx-x64-Release/build/include -I../../scripts/llvm-cad143-macosx-x64-Release/build/tools/clang/include -m64 -O2 -fPIC -g -fno-rtti -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/CppSharp.CppParser/AST.o" -MF "../obj/Release_x64/x64/Release/CppSharp.CppParser/AST.d" -c "../../../src/CppParser/AST.cpp"
Comments.cpp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.CppParser
clang++   -MMD -MP -DNDEBUG -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../../scripts/llvm-cad143-macosx-x64-Release/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/lib -I../../scripts/llvm-cad143-macosx-x64-Release/build/include -I../../scripts/llvm-cad143-macosx-x64-Release/build/tools/clang/include -m64 -O2 -fPIC -g -fno-rtti -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/CppSharp.CppParser/Comments.o" -MF "../obj/Release_x64/x64/Release/CppSharp.CppParser/Comments.d" -c "../../../src/CppParser/Comments.cpp"
CppParser.cpp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.CppParser
clang++   -MMD -MP -DNDEBUG -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../../scripts/llvm-cad143-macosx-x64-Release/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/lib -I../../scripts/llvm-cad143-macosx-x64-Release/build/include -I../../scripts/llvm-cad143-macosx-x64-Release/build/tools/clang/include -m64 -O2 -fPIC -g -fno-rtti -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/CppSharp.CppParser/CppParser.o" -MF "../obj/Release_x64/x64/Release/CppSharp.CppParser/CppParser.d" -c "../../../src/CppParser/CppParser.cpp"
Parser.cpp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.CppParser
clang++   -MMD -MP -DNDEBUG -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../../scripts/llvm-cad143-macosx-x64-Release/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/lib -I../../scripts/llvm-cad143-macosx-x64-Release/build/include -I../../scripts/llvm-cad143-macosx-x64-Release/build/tools/clang/include -m64 -O2 -fPIC -g -fno-rtti -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/CppSharp.CppParser/Parser.o" -MF "../obj/Release_x64/x64/Release/CppSharp.CppParser/Parser.d" -c "../../../src/CppParser/Parser.cpp"
Sources.cpp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.CppParser
clang++   -MMD -MP -DNDEBUG -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../../scripts/llvm-cad143-macosx-x64-Release/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/lib -I../../scripts/llvm-cad143-macosx-x64-Release/build/include -I../../scripts/llvm-cad143-macosx-x64-Release/build/tools/clang/include -m64 -O2 -fPIC -g -fno-rtti -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/CppSharp.CppParser/Sources.o" -MF "../obj/Release_x64/x64/Release/CppSharp.CppParser/Sources.d" -c "../../../src/CppParser/Sources.cpp"
Target.cpp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.CppParser
clang++   -MMD -MP -DNDEBUG -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../../scripts/llvm-cad143-macosx-x64-Release/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/include -I../../scripts/llvm-cad143-macosx-x64-Release/tools/clang/lib -I../../scripts/llvm-cad143-macosx-x64-Release/build/include -I../../scripts/llvm-cad143-macosx-x64-Release/build/tools/clang/include -m64 -O2 -fPIC -g -fno-rtti -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/CppSharp.CppParser/Target.o" -MF "../obj/Release_x64/x64/Release/CppSharp.CppParser/Target.d" -c "../../../src/CppParser/Target.cpp"
Linking CppSharp.CppParser
mkdir -p ../lib/Release_x64
clang++ -o "../lib/Release_x64/libCppSharp.CppParser.dylib" ../obj/Release_x64/x64/Release/CppSharp.CppParser/AST.o ../obj/Release_x64/x64/Release/CppSharp.CppParser/Comments.o ../obj/Release_x64/x64/Release/CppSharp.CppParser/CppParser.o ../obj/Release_x64/x64/Release/CppSharp.CppParser/Parser.o ../obj/Release_x64/x64/Release/CppSharp.CppParser/Sources.o ../obj/Release_x64/x64/Release/CppSharp.CppParser/Target.o    -L../../scripts/llvm-cad143-macosx-x64-Release/build/lib -m64 -dynamiclib -Wl,-install_name,@rpath/libCppSharp.CppParser.dylib -lc++ -lcurses -lpthread -lz -lclangFrontend -lclangDriver -lclangSerialization -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangAST -lclangLex -lclangBasic -lclangIndex -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMIRReader -lLLVMAsmParser -lLLVMOption -lLLVMInstrumentation -lLLVMProfileData -lLLVMX86AsmParser -lLLVMX86Desc -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMX86CodeGen -lLLVMX86Disassembler -lLLVMCodeGen -lLLVMSelectionDAG -lLLVMGlobalISel -lLLVMDebugInfoCodeView -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMAnalysis -lLLVMTarget -lLLVMMCDisassembler -lLLVMMC -lLLVMCoverage -lLLVMCore -lLLVMSupport -lLLVMBinaryFormat -lLLVMDemangle
Running postbuild commands
cp -rf /Users/kal/YetiCode/CppSharp/build/scripts/llvm-cad143-macosx-x64-Release/lib ../lib/Release_x64
==== Building Std-symbols (release_x64) ====
Std-symbols.cpp
mkdir -p ../obj/Release_x64/x64/Release/Std-symbols
clang++   -MMD -MP -DNDEBUG  -m64 -O2 -fPIC -g -fno-rtti -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/Std-symbols/Std-symbols.o" -MF "../obj/Release_x64/x64/Release/Std-symbols/Std-symbols.d" -c "../../../src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/Std-symbols.cpp"
Linking Std-symbols
mkdir -p ../lib/Release_x64
clang++ -o "../lib/Release_x64/libStd-symbols.dylib" ../obj/Release_x64/x64/Release/Std-symbols/Std-symbols.o    -m64 -dynamiclib -Wl,-install_name,@rpath/libStd-symbols.dylib -lc++
==== Building CppSharp.Runtime (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.Runtime
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.Runtime
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.Runtime/CppSharp.Runtime.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.Runtime.dll /unsafe /debug /noconfig /d:LIBCXX /t:library   /r:System @../obj/Release_x64/x64/Release/CppSharp.Runtime/CppSharp.Runtime.rsp
==== Building CppSharp.Parser.CSharp (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.Parser.CSharp
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.Parser.CSharp
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.Parser.CSharp/CppSharp.Parser.CSharp.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.Parser.CSharp.dll /unsafe /debug /noconfig /t:library  /r:../lib/Release_x64/CppSharp.Runtime.dll  @../obj/Release_x64/x64/Release/CppSharp.Parser.CSharp/CppSharp.Parser.CSharp.rsp
==== Building CppSharp.Parser (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.Parser
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.Parser
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.Parser/CppSharp.Parser.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.Parser.dll /unsafe /debug /noconfig /t:library  /r:../lib/Release_x64/CppSharp.dll /r:../lib/Release_x64/CppSharp.AST.dll /r:../lib/Release_x64/CppSharp.Parser.CSharp.dll /r:../lib/Release_x64/CppSharp.Runtime.dll /r:System /r:System.Core @../obj/Release_x64/x64/Release/CppSharp.Parser/CppSharp.Parser.rsp
==== Building CppSharp.Generator (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.Generator
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.Generator
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.Generator/CppSharp.Generator.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.Generator.dll /debug /noconfig /t:library  /r:../lib/Release_x64/CppSharp.dll /r:../lib/Release_x64/CppSharp.AST.dll /r:../lib/Release_x64/CppSharp.Parser.dll /r:../lib/Release_x64/CppSharp.Parser.CSharp.dll /r:../lib/Release_x64/CppSharp.Runtime.dll /r:System /r:System.Core @../obj/Release_x64/x64/Release/CppSharp.Generator/CppSharp.Generator.rsp /resource:../../../src/Generator/Passes/verbs.txt
../../../src/Generator/Generators/CSharp/CSharpSources.cs(1061,17): warning CS0219: The variable `prefix' is assigned but its value is never used
Compilation succeeded - 1 warning(s)
==== Building CppSharp.Parser.Gen (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.Parser.Gen
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.Parser.Gen
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.Parser.Gen/CppSharp.Parser.Gen.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.Parser.Gen.exe /debug /noconfig /t:exe  /r:../lib/Release_x64/CppSharp.dll /r:../lib/Release_x64/CppSharp.AST.dll /r:../lib/Release_x64/CppSharp.Generator.dll /r:../lib/Release_x64/CppSharp.Parser.dll /r:../lib/Release_x64/CppSharp.Parser.CSharp.dll /r:../lib/Release_x64/CppSharp.Runtime.dll /r:System.Core @../obj/Release_x64/x64/Release/CppSharp.Parser.Gen/CppSharp.Parser.Gen.rsp
==== Building CppSharp.CLI (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.CLI
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.CLI
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.CLI/CppSharp.CLI.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.CLI.exe /debug /noconfig /t:exe  /r:../lib/Release_x64/CppSharp.dll /r:../lib/Release_x64/CppSharp.AST.dll /r:../lib/Release_x64/CppSharp.Generator.dll /r:../lib/Release_x64/CppSharp.Parser.dll /r:../lib/Release_x64/CppSharp.Parser.CSharp.dll /r:../lib/Release_x64/CppSharp.Runtime.dll /r:System /r:System.Core @../obj/Release_x64/x64/Release/CppSharp.CLI/CppSharp.CLI.rsp
../../../src/CLI/CLI.cs(156,29): warning CS0168: The variable `ex' is declared but never used
Compilation succeeded - 1 warning(s)
==== Building CppSharp.Generator.Tests (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CppSharp.Generator.Tests
mkdir -p ../obj/Release_x64/x64/Release/CppSharp.Generator.Tests
Generating response file
rm -f ../obj/Release_x64/x64/Release/CppSharp.Generator.Tests/CppSharp.Generator.Tests.rsp
mcs /nologo /out:../lib/Release_x64/CppSharp.Generator.Tests.dll /debug /noconfig /t:library /lib:/Users/kal/YetiCode/CppSharp/deps/NUnit /lib:/Users/kal/YetiCode/CppSharp/deps/NSubstitute /r:../lib/Release_x64/CppSharp.Parser.CSharp.dll /r:../lib/Release_x64/CppSharp.Runtime.dll /r:../lib/Release_x64/CppSharp.dll /r:../lib/Release_x64/CppSharp.AST.dll /r:../lib/Release_x64/CppSharp.Generator.dll /r:../lib/Release_x64/CppSharp.Parser.dll /r:System /r:System.Core /r:nunit.framework /r:NSubstitute @../obj/Release_x64/x64/Release/CppSharp.Generator.Tests/CppSharp.Generator.Tests.rsp
==== Building CLI.Native (release_x64) ====
CLI.cpp
mkdir -p ../obj/Release_x64/x64/Release/CLI.Native
clang++   -MMD -MP -DNDEBUG  -m64 -O2 -fPIC -g -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/CLI.Native/CLI.o" -MF "../obj/Release_x64/x64/Release/CLI.Native/CLI.d" -c "../../../tests/CLI/CLI.cpp"
In file included from ../../../tests/CLI/CLI.cpp:1:
../../../tests/CLI/CLI.h:17:46: warning: calling convention 'stdcall' ignored for this target [-Wignored-attributes]
    typedef int AttributedFuncType(int, int) ATTR;
                                             ^
../../../tests/CLI/CLI.h:10:29: note: expanded from macro 'ATTR'
#define ATTR __attribute__((stdcall))
                            ^
1 warning generated.
Linking CLI.Native
mkdir -p ../lib/Release_x64
clang++ -o "../lib/Release_x64/libCLI.Native.dylib" ../obj/Release_x64/x64/Release/CLI.Native/CLI.o    -m64 -dynamiclib -Wl,-install_name,@rpath/libCLI.Native.dylib -lc++
==== Building CLI.Gen (release_x64) ====
Creating ../obj/Release_x64/x64/Release/CLI.Gen
mkdir -p ../obj/Release_x64/x64/Release/CLI.Gen
Generating response file
rm -f ../obj/Release_x64/x64/Release/CLI.Gen/CLI.Gen.rsp
mcs /nologo /out:../lib/Release_x64/CLI.Gen.exe /unsafe /debug /noconfig /t:exe  /r:../lib/Release_x64/CppSharp.dll /r:../lib/Release_x64/CppSharp.AST.dll /r:../lib/Release_x64/CppSharp.Generator.dll /r:../lib/Release_x64/CppSharp.Generator.Tests.dll /r:../lib/Release_x64/CppSharp.Parser.dll /r:../lib/Release_x64/CppSharp.Parser.CSharp.dll /r:../lib/Release_x64/CppSharp.Runtime.dll /r:System /r:System.Core @../obj/Release_x64/x64/Release/CLI.Gen/CLI.Gen.rsp
==== Building Common.Native (release_x64) ====
AnotherUnit.cpp
mkdir -p ../obj/Release_x64/x64/Release/Common.Native
clang++   -MMD -MP -DNDEBUG  -m64 -O2 -fPIC -g -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/Common.Native/AnotherUnit.o" -MF "../obj/Release_x64/x64/Release/Common.Native/AnotherUnit.d" -c "../../../tests/Common/AnotherUnit.cpp"
Common.cpp
mkdir -p ../obj/Release_x64/x64/Release/Common.Native
clang++   -MMD -MP -DNDEBUG  -m64 -O2 -fPIC -g -stdlib=libc++ -fpermissive -std=c++11  -o "../obj/Release_x64/x64/Release/Common.Native/Common.o" -MF "../obj/Release_x64/x64/Release/Common.Native/Common.d" -c "../../../tests/Common/Common.cpp"
In file included from ../../../tests/Common/Common.cpp:1:
../../../tests/Common/Common.h:369:14: warning: calling convention 'stdcall' ignored for this target [-Wignored-attributes]
typedef int (STDCALL *DelegateStdCall)(int);
             ^
../../../tests/Common/../Tests.h:17:32: note: expanded from macro 'STDCALL'
#define STDCALL __attribute__((stdcall))
                               ^
In file included from ../../../tests/Common/Common.cpp:1:
../../../tests/Common/Common.h:390:40: warning: calling convention 'stdcall' ignored for this target [-Wignored-attributes]
    int MarshalAnonymousDelegate5(int (STDCALL *del)(int n));
                                       ^
../../../tests/Common/../Tests.h:17:32: note: expanded from macro 'STDCALL'
#define STDCALL __attribute__((stdcall))
                               ^
In file included from ../../../tests/Common/Common.cpp:1:
../../../tests/Common/Common.h:391:40: warning: calling convention 'stdcall' ignored for this target [-Wignored-attributes]
    int MarshalAnonymousDelegate6(int (STDCALL *del)(int n));
                                       ^
../../../tests/Common/../Tests.h:17:32: note: expanded from macro 'STDCALL'
#define STDCALL __attribute__((stdcall))
                               ^
In file included from ../../../tests/Common/Common.cpp:1:
../../../tests/Common/Common.h:613:10: warning: 'setVirtual' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    void setVirtual(bool value);
         ^
../../../tests/Common/Common.h:586:18: note: overridden virtual function is here
    virtual void setVirtual(bool value);
                 ^
../../../tests/Common/Common.cpp:437:51: warning: calling convention 'stdcall' ignored for this target [-Wignored-attributes]
int TestDelegates::MarshalAnonymousDelegate5(int (STDCALL *del)(int))
                                                  ^
../../../tests/Common/../Tests.h:17:32: note: expanded from macro 'STDCALL'
#define STDCALL __attribute__((stdcall))
                               ^
../../../tests/Common/Common.cpp:442:51: warning: calling convention 'stdcall' ignored for this target [-Wignored-attributes]
int TestDelegates::MarshalAnonymousDelegate6(int (STDCALL *del)(int))
                                                  ^
../../../tests/Common/../Tests.h:17:32: note: expanded from macro 'STDCALL'
#define STDCALL __attribute__((stdcall))
                               ^
6 warnings generated.
Linking Common.Native
mkdir -p ../lib/Release_x64
clang++ -o "../lib/Release_x64/libCommon.Native.dylib" ../obj/Release_x64/x64/Release/Common.Native/AnotherUnit.o ../obj/Release_x64/x64/Release/Common.Native/Common.o    -m64 -dynamiclib -Wl,-install_name,@rpath/libCommon.Native.dylib -lc++
==== Building Common.Gen (release_x64) ====
Creating ../obj/Release_x64/x64/Release/Common.Gen
mkdir -p ../obj/Release_x64/x64/Release/Common.Gen
Generating response file
rm -f ../obj/Release_x64/x64/Release/Common.Gen/Common.Gen.rsp
mcs /nologo /out:../lib/Release_x64/Common.Gen.exe /unsafe /debug /noconfig /t:exe  /r:../lib/Release_x64/CppSharp.dll /r:../lib/Release_x64/CppSharp.AST.dll /r:../lib/Release_x64/CppSharp.Generator.dll /r:../lib/Release_x64/CppSharp.Generator.Tests.dll /r:../lib/Release_x64/CppSharp.Parser.dll /r:../lib/Release_x64/CppSharp.Parser.CSharp.dll /r:../lib/Release_x64/CppSharp.Runtime.dll /r:System /r:System.Core @../obj/Release_x64/x64/Release/Common.Gen/Common.Gen.rsp
```

- `Common.CSharp` produces exception:
```
==== Building Common.CSharp (release_x64) ====
Creating ../obj/Release_x64/x64/Release/Common.CSharp
mkdir -p ../obj/Release_x64/x64/Release/Common.CSharp
Running prebuild commands
mono64 --debug "../lib/Release_x64/Common.Gen.exe"

Generating bindings for Common (CLI)
Looking for tests in: /Users/kal/YetiCode/CppSharp/tests/Common
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) CppSharp.Parser.ClangParser/__Internal.ParseHeader (intptr) [0x00009] in <1416429af7a8479d8a41254c0607ea14>:0
  at CppSharp.Parser.ClangParser.ParseHeader (CppSharp.Parser.CppParserOptions) [0x0001f] in /Users/kal/YetiCode/CppSharp/src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/CppSharp.CppParser.cs:19099
  at CppSharp.ClangParser.ParseSourceFiles (System.Collections.Generic.IEnumerable`1<string>,CppSharp.Parser.ParserOptions) [0x00046] in /Users/kal/YetiCode/CppSharp/src/Parser/Parser.cs:66
  at CppSharp.Driver.ParseCode () [0x0007a] in /Users/kal/YetiCode/CppSharp/src/Generator/Driver.cs:208
  at CppSharp.ConsoleDriver.Run (CppSharp.ILibrary) [0x00090] in /Users/kal/YetiCode/CppSharp/src/Generator/Driver.cs:490
  at CppSharp.Tests.CommonTestsGenerator.Main (string[]) [0x00007] in /Users/kal/YetiCode/CppSharp/tests/Common/Common.cs:86
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x00051] in <2e478bd7a1b84b42a8197ed8ec3b01c3>:0

Native stacktrace:

	0   mono64                              0x000000010b333706 mono_handle_native_crash + 278
	1   mono64                              0x000000010b399446 altstack_handle_and_restore + 70
	2   libCppSharp.CppParser.dylib         0x000000010f1d110e _ZN8CppSharp9CppParser6Parser8WalkTypeEN5clang8QualTypeEPKNS2_7TypeLocEb + 2382
	3   libCppSharp.CppParser.dylib         0x000000010f1d7109 _ZN8CppSharp9CppParser6Parser20WalkTemplateArgumentERKN5clang16TemplateArgumentEPNS2_19TemplateArgumentLocE + 297
	4   libCppSharp.CppParser.dylib         0x000000010f1d5646 _ZN8CppSharp9CppParser6Parser24WalkTemplateArgumentListEPKN5clang20TemplateArgumentListEPNS2_29TemplateSpecializationTypeLocE + 422
	5   libCppSharp.CppParser.dylib         0x000000010f1d1e05 _ZN8CppSharp9CppParser6Parser8WalkTypeEN5clang8QualTypeEPKNS2_7TypeLocEb + 5701
	6   libCppSharp.CppParser.dylib         0x000000010f1d1097 _ZN8CppSharp9CppParser6Parser8WalkTypeEN5clang8QualTypeEPKNS2_7TypeLocEb + 2263
	7   libCppSharp.CppParser.dylib         0x000000010f1ced26 _ZN8CppSharp9CppParser6Parser15WalkDeclarationEPKN5clang4DeclEbb + 2070
	8   libCppSharp.CppParser.dylib         0x000000010f1d410d _ZN8CppSharp9CppParser6Parser10WalkRecordEPKN5clang10RecordDeclEPNS0_3AST5ClassE + 509
	9   libCppSharp.CppParser.dylib         0x000000010f1d39db _ZN8CppSharp9CppParser6Parser13WalkRecordCXXEPKN5clang13CXXRecordDeclEPNS0_3AST5ClassE + 75
	10  libCppSharp.CppParser.dylib         0x000000010f1d3869 _ZN8CppSharp9CppParser6Parser20EnsureCompleteRecordEPKN5clang10RecordDeclEPNS0_3AST18DeclarationContextEPNS6_5ClassE + 617
	11  libCppSharp.CppParser.dylib         0x000000010f1d45e9 _ZN8CppSharp9CppParser6Parser9GetRecordEPKN5clang10RecordDeclERb + 377
	12  libCppSharp.CppParser.dylib         0x000000010f1d53a0 _ZN8CppSharp9CppParser6Parser17WalkClassTemplateEPKN5clang17ClassTemplateDeclE + 400
	13  libCppSharp.CppParser.dylib         0x000000010f1ce6a3 _ZN8CppSharp9CppParser6Parser15WalkDeclarationEPKN5clang4DeclEbb + 403
	14  libCppSharp.CppParser.dylib         0x000000010f1d1053 _ZN8CppSharp9CppParser6Parser8WalkTypeEN5clang8QualTypeEPKNS2_7TypeLocEb + 2195
	15  libCppSharp.CppParser.dylib         0x000000010f1d989b _ZN8CppSharp9CppParser6Parser13WalkParameterEPKN5clang11ParmVarDeclERKNS2_14SourceLocationE + 299
	16  libCppSharp.CppParser.dylib         0x000000010f1d23a9 _ZN8CppSharp9CppParser6Parser8WalkTypeEN5clang8QualTypeEPKNS2_7TypeLocEb + 7145
	17  libCppSharp.CppParser.dylib         0x000000010f1d8a4a _ZN8CppSharp9CppParser6Parser12WalkFunctionEPKN5clang12FunctionDeclEPNS0_3AST8FunctionEb + 778
	18  libCppSharp.CppParser.dylib         0x000000010f1d2ddd _ZN8CppSharp9CppParser6Parser13WalkMethodCXXEPKN5clang13CXXMethodDeclE + 1197
	19  libCppSharp.CppParser.dylib         0x000000010f1d7716 _ZN8CppSharp9CppParser6Parser20WalkFunctionTemplateEPKN5clang20FunctionTemplateDeclE + 134
	20  libCppSharp.CppParser.dylib         0x000000010f1ce6b4 _ZN8CppSharp9CppParser6Parser15WalkDeclarationEPKN5clang4DeclEbb + 420
	21  libCppSharp.CppParser.dylib         0x000000010f1d410d _ZN8CppSharp9CppParser6Parser10WalkRecordEPKN5clang10RecordDeclEPNS0_3AST5ClassE + 509
	22  libCppSharp.CppParser.dylib         0x000000010f1d39db _ZN8CppSharp9CppParser6Parser13WalkRecordCXXEPKN5clang13CXXRecordDeclEPNS0_3AST5ClassE + 75
	23  libCppSharp.CppParser.dylib         0x000000010f1d3869 _ZN8CppSharp9CppParser6Parser20EnsureCompleteRecordEPKN5clang10RecordDeclEPNS0_3AST18DeclarationContextEPNS6_5ClassE + 617
	24  libCppSharp.CppParser.dylib         0x000000010f1d45e9 _ZN8CppSharp9CppParser6Parser9GetRecordEPKN5clang10RecordDeclERb + 377
	25  libCppSharp.CppParser.dylib         0x000000010f1d53a0 _ZN8CppSharp9CppParser6Parser17WalkClassTemplateEPKN5clang17ClassTemplateDeclE + 400
	26  libCppSharp.CppParser.dylib         0x000000010f1ce6a3 _ZN8CppSharp9CppParser6Parser15WalkDeclarationEPKN5clang4DeclEbb + 403
	27  libCppSharp.CppParser.dylib         0x000000010f1ce685 _ZN8CppSharp9CppParser6Parser15WalkDeclarationEPKN5clang4DeclEbb + 373
	28  libCppSharp.CppParser.dylib         0x000000010f1ce685 _ZN8CppSharp9CppParser6Parser15WalkDeclarationEPKN5clang4DeclEbb + 373
	29  libCppSharp.CppParser.dylib         0x000000010f1dbdc5 _ZN8CppSharp9CppParser6Parser11ParseHeaderERKNSt3__16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEEPNS0_12ParserResultE + 1621
	30  ???                                 0x0000000111f04a7d 0x0 + 4595927677
	31  ???                                 0x0000000111efed7e 0x0 + 4595903870
	32  ???                                 0x000000010b7a55fb 0x0 + 4487534075
	33  ???                                 0x000000010b7a50fc 0x0 + 4487532796
	34  mono64                              0x000000010b289d45 mono_jit_runtime_invoke + 2245
	35  mono64                              0x000000010b48ad18 do_runtime_invoke + 88
	36  mono64                              0x000000010b48e18c do_exec_main_checked + 140
	37  mono64                              0x000000010b2f8a1e mono_jit_exec + 302
	38  mono64                              0x000000010b2fae27 mono_main + 8167
	39  mono64                              0x000000010b27ae0a main + 1690
	40  mono64                              0x000000010b27a764 start + 52
	41  ???                                 0x0000000000000003 0x0 + 3
```

- Additional debug info from gdb (Is it possible my GDB is messed up because of using a xcode beta?):
```
Debug info from gdb:

(lldb) command source -s 0 '/tmp/mono-gdb-commands.hTcQho'
Executing commands in '/tmp/mono-gdb-commands.hTcQho'.
(lldb) process attach --pid 80197
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/4.5/mscorlib.dll.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Process 80197 stopped
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fffd7a843ee libsystem_kernel.dylib`__wait4 + 10
libsystem_kernel.dylib`__wait4:
->  0x7fffd7a843ee <+10>: jae    0x7fffd7a843f8            ; <+20>
    0x7fffd7a843f0 <+12>: movq   %rax, %rdi
    0x7fffd7a843f3 <+15>: jmp    0x7fffd7a7ccd4            ; cerror
    0x7fffd7a843f8 <+20>: retq

Executable module set to "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono64".
Architecture set to: x86_64h-apple-macosx.
(lldb) thread list
Process 80197 stopped
* thread #1: tid = 0x6aa80b, 0x00007fffd7a843ee libsystem_kernel.dylib`__wait4 + 10, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  thread #2: tid = 0x6aa80c, 0x00007fffd7a83bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'SGen worker'
  thread #3: tid = 0x6aa80d, 0x00007fffd7a7c386 libsystem_kernel.dylib`semaphore_wait_trap + 10, name = 'Finalizer'
  thread #4: tid = 0x6aa80e, 0x00007fffd7a8444e libsystem_kernel.dylib`__workq_kernreturn + 10
  thread #5: tid = 0x6aa80f, 0x00007fffd7a8444e libsystem_kernel.dylib`__workq_kernreturn + 10
  thread #6: tid = 0x6aa810, 0x00007fffd7a8444e libsystem_kernel.dylib`__workq_kernreturn + 10
(lldb) thread backtrace all
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fffd7a843ee libsystem_kernel.dylib`__wait4 + 10
    frame #1: 0x000000010b33379d mono64`mono_handle_native_crash(signal="SIGSEGV", ctx=<unavailable>, info=<unavailable>) at mini-exceptions.c:2558 [opt]
    frame #2: 0x000000010b399446 mono64`altstack_handle_and_restore(ctx=0x00007fff54985800, obj=0x0000000000000000, stack_ovf=0) at exceptions-amd64.c:790 [opt]
    frame #3: 0x000000010f1d110e libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(clang::QualType, clang::TypeLoc const*, bool) [inlined] clang::QualType::getCommonPtr() const at Type.h:633 [opt]
    frame #4: 0x000000010f1d110a libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(clang::QualType, clang::TypeLoc const*, bool) [inlined] clang::QualType::getTypePtr() const at Type.h:5488 [opt]
    frame #5: 0x000000010f1d110a libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(clang::QualType, clang::TypeLoc const*, bool) [inlined] clang::TypeLoc::getTypePtr() const at TypeLoc.h:119 [opt]
    frame #6: 0x000000010f1d110a libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(clang::QualType, clang::TypeLoc const*, bool) [inlined] clang::QualifiedTypeLoc::getUnqualifiedLoc() const at TypeLoc.h:262 [opt]
    frame #7: 0x000000010f1d110a libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(clang::QualType, clang::TypeLoc const*, bool) [inlined] clang::TypeLoc::getUnqualifiedLoc() const at TypeLoc.h:306 [opt]
    frame #8: 0x000000010f1d1106 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(this=<unavailable>, QualType=<unavailable>, TL=0x00007fff54985ae8, DesugarType=<unavailable>) at Parser.cpp:2380 [opt]
    frame #9: 0x000000010f1d7109 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkTemplateArgument(clang::TemplateArgument const&, clang::TemplateArgumentLoc*) [inlined] CppSharp::CppParser::Parser::GetQualifiedType(this=<unavailable>, TL=<unavailable>) at Parser.cpp:559 [opt]
    frame #10: 0x000000010f1d70fc libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkTemplateArgument(this=0x00007f931606db80, TA=0x00007fff54985b50, ArgLoc=<unavailable>) at Parser.cpp:1292 [opt]
    frame #11: 0x000000010f1d5646 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkTemplateArgumentList(this=0x00007f931606db80, TAL=0x00007fff54985c40, TSTL=0x00007fff54985c50) at Parser.cpp:1241 [opt]
    frame #12: 0x000000010f1d1e05 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(this=<unavailable>, QualType=<unavailable>, TL=0x00007fff54985e00, DesugarType=<unavailable>) at Parser.cpp:2403 [opt]
    frame #13: 0x000000010f1d1097 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(clang::QualType, clang::TypeLoc const*, bool) [inlined] CppSharp::CppParser::Parser::GetQualifiedType(this=0x00007f931606db80, TL=0x00007fff54985e00) at Parser.cpp:559 [opt]
    frame #14: 0x000000010f1d1081 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(this=<unavailable>, QualType=<unavailable>, TL=0x00007fff54985e00, DesugarType=<unavailable>) at Parser.cpp:2371 [opt]
    frame #15: 0x000000010f1ced26 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(clang::Decl const*, bool, bool) [inlined] CppSharp::CppParser::Parser::GetQualifiedType(this=0x00007f931606db80) at Parser.cpp:559 [opt]
    frame #16: 0x000000010f1ced0b libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(this=0x00007f931606db80, D=0x00007f9315ef3e90, CanBeDefinition=<unavailable>, WalkRedecls=<unavailable>) at Parser.cpp:3664 [opt]
    frame #17: 0x000000010f1d410d libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkRecord(this=0x00007f931606db80, Record=<unavailable>, RC=0x00007f931647c390) at Parser.cpp:903 [opt]
    frame #18: 0x000000010f1d39db libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkRecordCXX(this=0x00007f931606db80, Record=0x00007f9315ed0f30, RC=0x00007f931647c390) at Parser.cpp:934 [opt]
    frame #19: 0x000000010f1d3869 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::EnsureCompleteRecord(this=0x00007f931606db80, Record=0x00007f9315c3fe20, NS=<unavailable>, RC=0x00007f931646caf0) at Parser.cpp:747 [opt]
    frame #20: 0x000000010f1d45e9 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::GetRecord(this=<unavailable>, Record=0x00007f9315c3fe20, Process=0x00007fff549860a7) at Parser.cpp:786 [opt]
    frame #21: 0x000000010f1d53a0 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkClassTemplate(this=0x00007f931606db80, TD=0x00007f9315c3feb8) at Parser.cpp:1147 [opt]
    frame #22: 0x000000010f1ce6a3 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(this=0x00007f931606db80, D=0x00007f9315c3feb8, CanBeDefinition=false, WalkRedecls=true) at Parser.cpp:3526 [opt]
    frame #23: 0x000000010f1d1053 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(this=<unavailable>, QualType=<unavailable>, TL=0x00007fff54986260, DesugarType=<unavailable>) at Parser.cpp:2368 [opt]
    frame #24: 0x000000010f1d989b libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkParameter(clang::ParmVarDecl const*, clang::SourceLocation const&) [inlined] CppSharp::CppParser::Parser::GetQualifiedType(this=0x00007f931606db80, TL=<unavailable>) at Parser.cpp:559 [opt]
    frame #25: 0x000000010f1d9885 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkParameter(this=0x00007f931606db80, PVD=0x00007f9315c7e8d8, ParamStartLoc=0x00007fff549862d0) at Parser.cpp:2818 [opt]
    frame #26: 0x000000010f1d23a9 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkType(this=<unavailable>, QualType=<unavailable>, TL=<unavailable>, DesugarType=<unavailable>) at Parser.cpp:2314 [opt]
    frame #27: 0x000000010f1d8a4a libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkFunction(clang::FunctionDecl const*, CppSharp::CppParser::AST::Function*, bool) [inlined] CppSharp::CppParser::Parser::GetQualifiedType(this=0x00007f931606db80, TL=<unavailable>) at Parser.cpp:559 [opt]
    frame #28: 0x000000010f1d8a30 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkFunction(this=0x00007f931606db80, FD=0x00007f9315c7ec20, F=0x00007f9316469980, IsDependent=<unavailable>) at Parser.cpp:2886 [opt]
    frame #29: 0x000000010f1d2ddd libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkMethodCXX(this=<unavailable>, MD=<unavailable>) at Parser.cpp:1630 [opt]
    frame #30: 0x000000010f1d7716 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkFunctionTemplate(this=0x00007f931606db80, TD=0x00007f9315c7ecc8) at Parser.cpp:1377 [opt]
    frame #31: 0x000000010f1ce6b4 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(this=0x00007f931606db80, D=0x00007f9315c7ecc8, CanBeDefinition=false, WalkRedecls=true) at Parser.cpp:3550 [opt]
    frame #32: 0x000000010f1d410d libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkRecord(this=0x00007f931606db80, Record=<unavailable>, RC=0x00007f9316448210) at Parser.cpp:903 [opt]
    frame #33: 0x000000010f1d39db libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkRecordCXX(this=0x00007f931606db80, Record=0x00007f9315c6d828, RC=0x00007f9316448210) at Parser.cpp:934 [opt]
    frame #34: 0x000000010f1d3869 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::EnsureCompleteRecord(this=0x00007f931606db80, Record=0x00007f93150b2a68, NS=<unavailable>, RC=0x00007f931643ec10) at Parser.cpp:747 [opt]
    frame #35: 0x000000010f1d45e9 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::GetRecord(this=<unavailable>, Record=0x00007f93150b2a68, Process=0x00007fff54986867) at Parser.cpp:786 [opt]
    frame #36: 0x000000010f1d53a0 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkClassTemplate(this=0x00007f931606db80, TD=0x00007f93150b2b00) at Parser.cpp:1147 [opt]
    frame #37: 0x000000010f1ce6a3 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(this=0x00007f931606db80, D=0x00007f93150b2b00, CanBeDefinition=true, WalkRedecls=true) at Parser.cpp:3526 [opt]
    frame #38: 0x000000010f1ce685 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(clang::Decl const*, bool, bool) [inlined] CppSharp::CppParser::Parser::WalkDeclarationDef(this=0x00007f931606db80, D=0x00007f93150b2b00) at Parser.cpp:3464 [opt]
    frame #39: 0x000000010f1ce670 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(this=0x00007f931606db80, D=0x00007f93150b28a0, CanBeDefinition=<unavailable>, WalkRedecls=true) at Parser.cpp:3684 [opt]
    frame #40: 0x000000010f1ce685 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(clang::Decl const*, bool, bool) [inlined] CppSharp::CppParser::Parser::WalkDeclarationDef(this=0x00007f931606db80, D=0x00007f93150b28a0) at Parser.cpp:3464 [opt]
    frame #41: 0x000000010f1ce670 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::WalkDeclaration(this=0x00007f931606db80, D=0x00007f93150b2838, CanBeDefinition=<unavailable>, WalkRedecls=true) at Parser.cpp:3684 [opt]
    frame #42: 0x000000010f1dbdc5 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::ParseHeader(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, CppSharp::CppParser::ParserResult*) [inlined] CppSharp::CppParser::Parser::WalkDeclarationDef(this=<unavailable>, D=<unavailable>) at Parser.cpp:3464 [opt]
    frame #43: 0x000000010f1dbda4 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::ParseHeader(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, CppSharp::CppParser::ParserResult*) [inlined] CppSharp::CppParser::Parser::WalkAST(this=0x00007f931606db80) at Parser.cpp:3059 [opt]
    frame #44: 0x000000010f1dbd88 libCppSharp.CppParser.dylib`CppSharp::CppParser::Parser::ParseHeader(this=0x00007f931606db80, SourceFiles=<unavailable>, res=<unavailable>) at Parser.cpp:3963 [opt]
    frame #45: 0x0000000111f04a7d
    frame #46: 0x0000000111efed7e
    frame #47: 0x000000010b7a55fb
    frame #48: 0x000000010b7a50fc
    frame #49: 0x000000010b289d45 mono64`mono_jit_runtime_invoke(method=<unavailable>, obj=0x0000000000000000, params=<unavailable>, error=<unavailable>) at mini-runtime.c:2546 [opt]
    frame #50: 0x000000010b48ad18 mono64`do_runtime_invoke(method=0x00007f9314603218, obj=0x0000000000000000, params=0x00007fff549873f0, exc=0x0000000000000000, error=0x00007fff54987440) at object.c:2829 [opt]
    frame #51: 0x000000010b48e18c mono64`do_exec_main_checked [inlined] mono_runtime_invoke_checked(method=0x00007f9314603218, obj=<unavailable>, params=0x000000010b800608, error=0x00007fff54987440) at object.c:2983 [opt]
    frame #52: 0x000000010b48e14b mono64`do_exec_main_checked(method=0x00007f9314603218, args=<unavailable>, error=0x00007fff54987440) at object.c:4623 [opt]
    frame #53: 0x000000010b2f8a1e mono64`mono_jit_exec(domain=<unavailable>, assembly=<unavailable>, argc=1, argv=0x00007fff54987880) at driver.g.c:1040 [opt]
    frame #54: 0x000000010b2fae27 mono64`mono_main [inlined] main_thread_handler at driver.g.c:1109 [opt]
    frame #55: 0x000000010b2fadf0 mono64`mono_main(argc=<unavailable>, argv=<unavailable>) at driver.g.c:2247 [opt]
    frame #56: 0x000000010b27ae0a mono64`main [inlined] mono_main_with_options(argc=3, argc=3, argc=3, argv=0x00007fff54987870, argv=0x00007fff54987870, argv=0x00007fff54987870) at main.c:46 [opt]
    frame #57: 0x000000010b27adf9 mono64`main(argc=3, argv=0x00007fff54987870) at main.c:339 [opt]
    frame #58: 0x000000010b27a764 mono64`start + 52

  thread #2, name = 'SGen worker'
    frame #0: 0x00007fffd7a83bf2 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fffd7b6f7fa libsystem_pthread.dylib`_pthread_cond_wait + 712
    frame #2: 0x000000010b5017f5 mono64`thread_func [inlined] mono_os_cond_wait(mutex=0x000000010b6577b8) at mono-os-mutex.h:173 [opt]
    frame #3: 0x000000010b5017e6 mono64`thread_func(thread_data=0x000000010b799108) at sgen-thread-pool.c:130 [opt]
    frame #4: 0x00007fffd7b6e93b libsystem_pthread.dylib`_pthread_body + 180
    frame #5: 0x00007fffd7b6e887 libsystem_pthread.dylib`_pthread_start + 286
    frame #6: 0x00007fffd7b6e08d libsystem_pthread.dylib`thread_start + 13

  thread #3, name = 'Finalizer'
    frame #0: 0x00007fffd7a7c386 libsystem_kernel.dylib`semaphore_wait_trap + 10
    frame #1: 0x000000010b483673 mono64`finalizer_thread [inlined] mono_os_sem_wait(flags=MONO_SEM_FLAGS_ALERTABLE) at mono-os-semaphore.h:91 [opt]
    frame #2: 0x000000010b483668 mono64`finalizer_thread [inlined] mono_coop_sem_wait(flags=MONO_SEM_FLAGS_ALERTABLE) at mono-coop-semaphore.h:43 [opt]
    frame #3: 0x000000010b483660 mono64`finalizer_thread(unused=<unavailable>) at gc.c:864 [opt]
    frame #4: 0x000000010b456c9b mono64`start_wrapper [inlined] start_wrapper_internal at threads.c:829 [opt]
    frame #5: 0x000000010b456c01 mono64`start_wrapper(data=<unavailable>) at threads.c:891 [opt]
    frame #6: 0x00007fffd7b6e93b libsystem_pthread.dylib`_pthread_body + 180
    frame #7: 0x00007fffd7b6e887 libsystem_pthread.dylib`_pthread_start + 286
    frame #8: 0x00007fffd7b6e08d libsystem_pthread.dylib`thread_start + 13

  thread #4
    frame #0: 0x00007fffd7a8444e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fffd7b6e48e libsystem_pthread.dylib`_pthread_wqthread + 1023
    frame #2: 0x00007fffd7b6e07d libsystem_pthread.dylib`start_wqthread + 13

  thread #5
    frame #0: 0x00007fffd7a8444e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fffd7b6e621 libsystem_pthread.dylib`_pthread_wqthread + 1426
    frame #2: 0x00007fffd7b6e07d libsystem_pthread.dylib`start_wqthread + 13

  thread #6
    frame #0: 0x00007fffd7a8444e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fffd7b6e621 libsystem_pthread.dylib`_pthread_wqthread + 1426
    frame #2: 0x00007fffd7b6e07d libsystem_pthread.dylib`start_wqthread + 13
(lldb) detach

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Process 80197 detached
(lldb) quit
make[1]: *** [prebuild] Abort trap: 6
make: *** [Common.CSharp] Error 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
```

**Comment by ddobrev** [comment]
@tritao any idea about this one?

**Comment by tritao** [comment]
Hmm, this does not look good. My guess is an ABI regression in the latest Clang toolchain, IIRC the Mono VM also had some issues related to it, I think it changed the way value types are passed or something. Or it could be something else.

I assume you're using the latest Xcode. Could try building with an older version (you can use `xcode-select` to switch between them)?

**Comment by KallynGowdyYetiCGI** [comment]
Ok, I'm gonna try 8.1 and 7.3.1.

@tritao Any other suggestions if those don't work? (Keep trying older and older versions?)

**Comment by tritao** [comment]
At least Xcode 8.2 should work, since thats what I am using.

See this issue where we debugged something similar: https://github.com/mono/CppSharp/issues/655

Might give you some ideas to help debug.

**Comment by tritao** [comment]
Did it work after all?

**Comment by KallynGowdyYetiCGI** [comment]
@tritao No. I think there's something wrong with my setup. I haven't been able to spend much time looking at this but my idea from here is to test on another Mac with Xcode 8.2 to see if I can get it to build.

**Comment by tritao** [comment]
Hmm, I just took a look again at the stack trace. Forget what I said about ABI regressions.

This looks familiar to some template parsing crashes we just fixed, please try again with master revision when you have a chance.

**Comment by KallynGowdyYetiCGI** [comment]
Still fails for me on [b395d21](https://github.com/mono/CppSharp/commit/b395d21e63309f93daf6e65a87e311e8182f077a). Looks like the same issue as well based on the stack trace.

**Comment by paulrouget** [comment]
Same issue here on #c818f08e.

**Comment by tritao** [comment]
@paulrouget Which Xcode version?

**Comment by paulrouget** [comment]
Version 9.0 (9A235)

**Comment by paulrouget** [comment]
Anything I can do to help fix this?

**Comment by tritao** [comment]
The process is probably the same as this one: https://github.com/mono/CppSharp/issues/726#issuecomment-339791008

**Comment by KallynGowdyYetiCGI** [comment]
FYI I just tried building using 0.8.16 ([`71381d3`](https://github.com/mono/CppSharp/commit/71381d3967ac9744110ba7a840bf3421aedc3420)) and it succeeded.

Note that I'm now using Xcode 9.1 (9B55), so that may have fixed things.

**Comment by ddobrev** [comment]
@KallynGowdyYetiCGI we've updated to a new Clang built with Xcode 9.1 so this might be the reason it works now.
